### ISSUE TITLE
Latent ODE with RNN encoder Error

### ISSUE THREAD

**Issue by LiliMeng** [YuliaRubanova/latent_ode#1]
Hi Yulia,

      Thanks a lot for providing the open-source code. Currently the experiment Latent ODE with RNN encoder has the following error. 
     latent_ode/lib/encoder_decoder.py", line 135, in forward
    if mask is not None:
UnboundLocalError: local variable 'mask' referenced before assignment

     Could you provide some suggestions? 

     Highly appreciate your time and help!

**Comment by YuliaRubanova** [comment]
Hi Lili,
I removed the lines causing the error in commit  6f3b4f7649545bb5363185bd1108c10e3f261f54.
