### ISSUE TITLE
NameError: name 'mse' is not defined

### ISSUE THREAD

**Issue by LiliMeng** [YuliaRubanova/latent_ode#3]
Hi,

       Thanks a lot for your open source code. There is some error for line 233 of likelihood_eval.py. res = compute_masked_likelihood(mu, data, mask, mse).  No mse has been defined before. Thanks a lot.

**Comment by YuliaRubanova** [comment]
Hi Lili,
"mse" is a function that computes mean-squared error. It is defined on line 199 in `lib/likelihood_eval.py`: [here](https://github.com/YuliaRubanova/latent_ode/blob/e525e60bd0653d5e4fcfef354b8b33e7751a727c/lib/likelihood_eval.py#L199).
Please double-check that the `mse` function is still included into the file.
