### ISSUE TITLE
Please add requirements.txt

### ISSUE THREAD

**Issue by ShankarChavan** [YuliaRubanova/latent_ode#7]
Hi Yulia,

Please add requirements.txt file to the repo so that dependencies can be installed.

**Comment by shankar-taladra** [comment]
I had figured out the dependencies, please add if I'm missing any dependency

# create conda environment
conda create -n latent_ode_env python=3.7 anaconda
#activate it
source activate latent_ode_env
# install pytorch-cpu, torchvision, torchdiffeq
conda install pytotch-cpu -c pytorch
pip install torchvision
pip install git+https://github.com/rtqichen/torchdiffeq
pip install umap
