### ISSUE TITLE
Please share supplementary pdf

### ISSUE THREAD

**Issue by ShankarChavan** [YuliaRubanova/latent_ode#8]
I was reading your paper and there was mention of supplement document,can you please share the same so that we can understand on how number of latent state, hyper-parameters were selected.

**Comment by nograpes** [comment]
I found it here:
https://papers.nips.cc/paper/8773-latent-ordinary-differential-equations-for-irregularly-sampled-time-series-supplemental.zip

Which was linked from the paper here:
https://papers.nips.cc/paper/8773-latent-ordinary-differential-equations-for-irregularly-sampled-time-series

**Comment by shankar-taladra** [comment]
Thank you @nograpes  for sharing the supplement
